# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Research"
#  url = "publication/"
  weight = 2

[[main]]
    parent = "Research"
    name = "Overview"
    url = "projects/"
    weight = 1

[[main]]
    parent = "Research"
    name = "Publications"
    url = "publications/"
    weight = 2

[[main]]
    parent = "Research"
    name = "CV"
    url = "/files/nowlin-cv-short.pdf/"
    weight = 3

#[[main]]
#  name = "Publications"
#  url = "publication/"
#  weight = 30

[[main]]
  name = "Teaching"
  url = "courses/"
  weight = 4

[[main]]
  name = "News & Notes"
  url = "post/"
  weight = 5

# [[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 50

# [[main]]
#   name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
